### PR TITLE
Move the login time to check earlier

### PR DESCRIPTION
**Pull request by DustinChaloupka**
The login time that we were checking for the app to be up within a
threshold was after a few calculations, this just moves it slightly earlier

### CODE REVIEW

**Comment by DustinChaloupka** [comment]
retest this please

**Comment by adamdecaf** [comment]
:+1: Were we running into a spot where it was being calculated too late?

**Comment by DustinChaloupka** [comment]
@adamdecaf Yeah, the some jenkins builds were failing because they weren't "up within the threshold", and to me this is more accurate on the time that the app is trying to log in anyways.

**Comment by DustinChaloupka** [comment]
retest this please

**Pull request merged**
