### PR TITLE
Update to 0.4.1

### PR DESCRIPTION
**Pull request by lamdor**
Rebased our one marathon auth commit onto https://github.com/hashicorp/vault/tree/v0.4.0

I also tested vault-setup against this, but haven't yet tested against env-setup.

Connect to Banno/infrastructure#143

### CODE REVIEW

**Comment by lamdor** [comment]
retest this please

**Comment by lamdor** [comment]
Not sure exactly why the jenkins pr build is totally failing. I'll look into that.

While testing env-setup, it turns out that upgrading will affect vault HA as it changed the way it advertises the hostname. It's using the short hostname instead of the full one now. So the standby can't send things off to the leader quite right. I haven't tested fully the non-HA case yet. It works with just simple write/reads.

**Comment by lamdor** [comment]
This PR isn't mergable but will require us to reset the Banno branch to this PR's HEAD since we just rebase our commits on top.

**Comment by lamdor** [comment]
After this can be merged/reset, I need to push up new docker vault images.

**Comment by sherzberg** [comment]
:+1:

**Comment by lamdor** [comment]
docker images are pushed

**Pull request merged**
