### PR TITLE
Bump auth timeframe up to 5 minutes

### PR DESCRIPTION
**Pull request by DustinChaloupka**
From stand up, we discussed putting this at a time that we do not have to fight against what the right time is, instead, make it a time we know will pass then push it down.

### CODE REVIEW

**Comment by adamdecaf** [comment]
👍

**Comment by adamdecaf** [comment]
@DustinChaloupka Do we need to change around the stored dependency versions? It looks like the marathon library changed.

**Comment by DustinChaloupka** [comment]
Hmm, but both of the errors are not true.... https://github.com/gambol99/go-marathon/blob/master/application.go#L178 and https://github.com/gambol99/go-marathon/blob/a78e3aa5d5ca7d5b14eafc3239d61bb53af17434/application.go#L535... guess I'll take a closer look tomorrow.

**Comment by DustinChaloupka** [comment]
Ok, this should be fixed up now and tests passed locally:

```
PASS
ok      github.com/hashicorp/vault/builtin/credential/marathon  71.581s
```

Just required updating the `go-marathon` ref version. I also fixed the tests since a `default` policy seems to have been added and a little sleep since the tests were running to quickly so while one was at the very end of being torn down, it would try to start the next one.

**Comment by DustinChaloupka** [comment]
retest this please

**Comment by sherzberg** [comment]
👍

**Pull request merged**
